apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-internal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
      - name: internal
        image: jay899/int:33
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: internal-svc
spec:
  selector:
    app: internal
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
